src/Entity/Chat.php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Serializer\Annotation\Groups;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ChatRepository;
use App\Repository\ParticipantRepository;
use App\Repository\ChatMessageRepository;
use App\Services\ImagesManager\ImagesConstants;

/**
 * @ORM\Entity(repositoryClass=ChatRepository::class)
 */
class Chat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"chat:message", "chat:list"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublic;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\OneToOne(targetEntity=ChatMessage::class, cascade={"persist", "remove"})
     * @Groups({"chat:list"})
     */
    private $lastMessage;

    /**
     * @ORM\OneToMany(targetEntity=ChatMessage::class, mappedBy="chat", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="chat", orphanRemoval=true, cascade={"persist", "remove"})
     * @Groups({"chat:participants"})
     * @MaxDepth(3)
     */
    private $participants;

    /**
     * @Gedmo\Timestampable(on="create")
     * @Gedmo\Timestampable(on="change", field={"messages", "title"})
     * @ORM\Column(type="datetime")
     */
    private $lastActivityAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getLastMessage(): ?ChatMessage
    {
        return $this->lastMessage;
    }

    public function setLastMessage(?ChatMessage $lastMessage): self
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * @return Collection|ChatMessage[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(ChatMessage $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setChat($this);
        }

        return $this;
    }

    public function removeMessage(ChatMessage $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getChat() === $this) {
                $message->setChat(null);
            }
        }

        return $this;
    }

    /**
     * getMessagesBetween   Get chat messages between start and stop date 
     * @param \DateTimeInterface    $startDate      Start date of messages to get
     * @param \DateTimeInterface    $stopDate       Stop date of messages to get
     * @return Collection|Message[]
     */
    public function getMessagesBetween(\DateTimeInterface $startDate, \DateTimeInterface $stopDate): Collection
    {
        $criteria = ChatMessageRepository::createBetweenDatesCriteria($startDate, $stopDate);

        return $this->messages->matching($criteria);
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setChat($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getChat() === $this) {
                $participant->setChat(null);
            }
        }

        return $this;
    }

    /**
     * getOtherParticipants Get chat participants without given user 
     * @param   User      $user       User object which should be not included to participants list
     * @return  Collection|Participant[]
     */
    public function getOtherParticipants(User $user): Collection
    {
        $criteria = ParticipantRepository::createNotIncludedUserCriteria($user);

        return $this->participants->matching($criteria);
    }

    /**
     * isCurrentParticipantRemoved      Check is participant with given user removed
     * @param   User      $user         User object which should be participant
     * @return  ?bool                   Return bool or null if user is not a participant of chat
     */
    public function isCurrentParticipantRemoved(User $user): ?bool
    {
        foreach ($this->participants as $participant) {
            if ($participant->getUser() ===  $user) {
                return $participant->getIsRemoved();
            }
        }

        return null;
    }

    /**
     * hasParticipant Check chat has participant with given user
     * @param   User      $user       User object which should be participant
     * @return  bool
     */
    public function hasParticipant(User $user): bool
    {
        foreach ($this->participants as $participant) {
            if ($participant->getUser() ===  $user) {
                return true;
            }
        }

        return false;
    }

    public function getLastActivityAt(): ?\DateTimeInterface
    {
        return $this->lastActivityAt;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return ImagesConstants::CHATS_IMAGES.'/'.$this->getOwner()->getLogin().'/'.$this->getImageFilename();
    }

    public function getThumbImagePath(): ?string
    {
        return ImagesConstants::CHATS_IMAGES.'/'.$this->getOwner()->getLogin().'/'.ImagesConstants::THUMB_IMAGES.'/'.$this->getImageFilename();
    }

}

src/Entity/MessageAttachment.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Services\AttachmentFileUploader\AttachmentsConstants;
use App\Services\ImagesManager\ImagesConstants;
use App\Repository\MessageAttachmentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageAttachmentRepository::class)
 */
class MessageAttachment extends Attachment
{

    /**
     * @ORM\ManyToOne(targetEntity=Message::class, inversedBy="attachments")
     */
    private $message;

    public function getMessage(): ?Message
    {
        return $this->message;
    }

    public function setMessage(?Message $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return ImagesConstants::ATTACHMENTS_IMAGES . '/' . ImagesConstants::CHATS_IMAGES . '/' . $this->user->getLogin() . '/' . $this->getFilename();
    }

    public function getThumbImagePath(): ?string
    {
        return ImagesConstants::ATTACHMENTS_IMAGES . '/' . ImagesConstants::CHATS_IMAGES . '/' . $this->user->getLogin() . '/' . ImagesConstants::THUMB_IMAGES . '/' . $this->getFilename();
    }

    public function getFilePath(): ?string
    {
        return AttachmentsConstants::ATTACHMENTS_FILES . '/' . AttachmentsConstants::CHATS_FILES . '/' . $this->user->getLogin() . '/' . $this->getFilename();
    }

}

src/Entity/Petition.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\PetitionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Model\Petition\PetitionConstants;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PetitionRepository::class)
 */
class Petition
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="petitions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $petitioner;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=PetitionMessage::class, mappedBy="petition", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $petitionMessages;

    /**
     * @ORM\OneToMany(targetEntity=PetitionAttachment::class, mappedBy="petition", orphanRemoval=true)
     */
    private $attachments;

    public function __construct()
    {
        $this->petitionMessages = new ArrayCollection();
        $this->attachments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * getTypeDescription Get full description of given type
     * @return string
     */
    public function getTypeDescription(): ?string
    {
        return array_keys(PetitionConstants::TYPES_DESC, $this->type, true)[0];
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPetitioner(): ?User
    {
        return $this->petitioner;
    }

    public function setPetitioner(?User $petitioner): self
    {
        $this->petitioner = $petitioner;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|PetitionMessage[]
     */
    public function getPetitionMessages(): Collection
    {
        return $this->petitionMessages;
    }

    public function addPetitionMessage(PetitionMessage $petitionMessage): self
    {
        if (!$this->petitionMessages->contains($petitionMessage)) {
            $this->petitionMessages[] = $petitionMessage;
            $petitionMessage->setPetition($this);
        }

        return $this;
    }

    public function removePetitionMessage(PetitionMessage $petitionMessage): self
    {
        if ($this->petitionMessages->contains($petitionMessage)) {
            $this->petitionMessages->removeElement($petitionMessage);
            // set the owning side to null (unless already changed)
            if ($petitionMessage->getPetition() === $this) {
                $petitionMessage->setPetition(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PetitionAttachment[]
     */
    public function getAttachments(): Collection
    {
        return $this->attachments;
    }

    public function addAttachment(PetitionAttachment $attachment): self
    {
        if (!$this->attachments->contains($attachment)) {
            $this->attachments[] = $attachment;
            $attachment->setPetition($this);
        }

        return $this;
    }

    public function removeAttachment(PetitionAttachment $attachment): self
    {
        if ($this->attachments->contains($attachment)) {
            $this->attachments->removeElement($attachment);
            // set the owning side to null (unless already changed)
            if ($attachment->getPetition() === $this) {
                $attachment->setPetition(null);
            }
        }

        return $this;
    }

}

templates/petition/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat - Add Petition{% endblock %}

{% block section_class %}petitionAdd{% endblock %} 
{% block content_class %}justify-content-center align-items-center{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('css/_forms.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/dropzone.min.css">
{% endblock %}

{% block content %}
<div class="col-12">
    <a href="{{ path('support_petition')}}" class="btn btn-info float-left">
        <span class="far fa-list-alt"></span>
    </a>
</div>
<div class="col-sm-6 text-center my-3">
    {{ include('forms/petition_form.html.twig', {
        header_text: 'New petition',
        button_text: 'Send'
    }) }}

    {% include 'modals/add_attachments_modal.html.twig' %}
</div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/dropzone.min.js"></script>
    <script type="module" src="{{ asset('js/helpers/_formHelper.js') }}"></script>
    <script type="module" src="{{ asset('js/_addAttachmentsDropzone.js') }}"></script>

{% endblock %}

templates/petition/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat - Petitions{% endblock %}

{% block section_class %}petitions{% endblock %} 
{% block content_class %}{% endblock %}
{% block content %}
{% do pagination.setSortableTemplate('paginator/sortable_button.html.twig') %}

<div class="col-sm-12 text-center mt-5">
    {% if pagination.getTotalItemCount > 0 %}
        <h2 class="mb-3 font-weight-normal text-uppercase text-purple">
            Your petitions ({{ pagination.getTotalItemCount }})
        </h2>
        <a href="{{ path('support_petition_add') }}" class="d-inline-block btn btn-primary float-right" data-toggle="tooltip" data-placement="top" title="Create new petition">
            Create
            <span class="fas fa-plus-circle"></span>
        </a>
        <div class="col-sm-12 col-md-4 mx-auto mb-2">
            {{ knp_pagination_filter(pagination, {}) }}
        </div>
            <div class="list my-3">
                <div class="row">
                    <div class="col-sm-12 text-left">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12">
                                        <h5 class="text-purple text-uppercase d-inline-block">Filter</h5>
                                        <a href="{{ path('support_petition')}}" class="btn btn-primary d-inline-block">All</a>
                                        {% for key, petitionType in petitionTypes %}
                                            <a href="{{ path('support_petition', { 'filterField': 'p.type', 'filterValue': petitionType }) }}" class="btn btn-primary d-inline-block">
                                                {{ key }}
                                            </a>
                                        {% endfor %}
                                    </div>
                                    <div class="col-12 mt-2">
                                        <h5 class="text-purple text-uppercase d-inline-block">Sort</h5>
                                        {{ knp_pagination_sortable(pagination, 'Reason', 'p.type', { 'class': 'text-decoration-none' }) }}
                                        {{ knp_pagination_sortable(pagination, 'Date', 'p.createdAt', { 'class': 'text-decoration-none' }) }}
                                        {{ knp_pagination_sortable(pagination, 'Status', 'p.status', { 'class': 'text-decoration-none' }) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for petition in pagination %}
                        <div class="col-md-4 my-3">
                            <div class="card text-center">  
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-12 text-right text-primary">
                                            {% if petition.status is same as('Pending') %}
                                                <span class="fa-stack" data-toggle="tooltip" data-placement="top" title="Sended">
                                                    <span class="fas fa-arrow-down fa-xs" style="vertical-align:top;"></span>
                                                    <span class="fas fa-user fa-sm"></span>
                                                </span>
                                            {% elseif petition.status is same as('Opened') %}
                                                <span class="fa-stack" data-toggle="tooltip" data-placement="top" title="Readed">
                                                    <span class="fas fa-eye fa-xs" style="vertical-align:top;"></span>
                                                    <span class="fas fa-user fa-sm"></span>
                                                </span>
                                            {% elseif petition.status is same as('Answered') %}
                                                <span class="fa-stack" data-toggle="tooltip" data-placement="top" title="Answered">
                                                    <span class="fas fa-envelope fa-xs" style="vertical-align:top;"></span>
                                                    <span class="fas fa-user fa-sm"></span>
                                                </span>
                                            {% elseif petition.status is same as('Closed') %}
                                                <span class="fas fa-lock text-success" data-toggle="tooltip" data-placement="top" title="Closed">
                                                </span>
                                            {% endif %}
                                        </div>
                                        <div class="col-12">
                                            <h5 class="text-orange">
                                                {{ petition.typeDescription }}
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title text-purple">
                                        {{ petition.title | u.truncate(40, '...') }}
                                    </h5>
                                    <p class="card-text text-muted">
                                        {{ petition.description | u.truncate(40, '...') }}
                                    </p>
                                    <a href="{{ path('support_petition_show', {id: petition.id}) }}" class="btn btn-primary">View</a>
                                </div>
                                <div class="card-footer text-muted">
                                    {{ time_diff(petition.createdAt) }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        <div class="navigation">
            {{ knp_pagination_render(pagination, null, {}, {
                'align': 'center'
            }) }}
            {{ include('paginator/per_page.html.twig', {
                span_color: 'text-primary',
                per_page: [6,12,18]
            }) }}
        </div>
    {% else %}
        <h2 class="mb-3 font-weight-normal text-uppercase text-purple">
            Your petitions
        </h2>
        <div class="col-sm-12 col-md-4 mx-auto mb-2">
            {{ knp_pagination_filter(pagination, {}) }}
        </div>
        {% include 'empty_table.html.twig' %}
    {% endif %}
</div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip({trigger: 'hover'});
            $('[data-toggle="tooltip"]').on('click', function () {
                $(this).tooltip('hide')
            });
        });
    </script>
{% endblock %}

templates/petition/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chat - Show Petition{% endblock %}

{% block section_class %}petitionShow{% endblock %} 
{% block content_class %}justify-content-center align-items-center{% endblock %}
{% block content_id %}js-petition-wrapper{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('css/_forms.css') }}">
{% endblock %}

{% block content %}
<div class="col-12 text-center">
    {% if petition.status is not same as('Closed') %}
        <a href="{{ path('support_petition')}}" class="btn btn-info float-left">
            <span class="far fa-list-alt"></span>
        </a>
        <button class="btn btn-danger float-right" role="button" id="js-close-petition">
            <span class="fas fa-lock"></span>
        </button>
    {% else %}
        <a href="{{ path('support_petition')}}" class="btn btn-info float-left">
            <span class="far fa-list-alt"></span>
        </a>
        <b class="text-danger text-uppercase">This petition is closed</b>
    {% endif %}
</div>
<div class="col-md-10 text-center my-3">
    <div class="card">
        <div class="card-header text-purple">
            <b>{{ petition.title }}</b>
        </div>
        <div class="card-body text-left">
            <p class="card-text">
                {{ petition.description }}
            </p>
            {% if petition.attachments is not empty %}
                <span><b>Attachments:</b></span>
                {% for attachment in petition.attachments %}
                    <span class="d-block">
                        {% if attachment.type is same as('Image') %}
                            <a href="{{ uploaded_asset(attachment.imagePath) }}">
                                <span class="fas fa-thumbtack"></span>
                                {{ attachment.filename }}
                            </a>
                        {% elseif attachment.type is same as('File') %}
                            <a href="{{ uploaded_asset(attachment.filePath) }}">
                                <span class="fas fa-thumbtack"></span>
                                {{ attachment.filename }}
                            </a>
                        {% endif %}
                    </span>
                {% endfor %}
            {% endif %}
        </div>
        <div class="card-footer text-right text-muted">{{ time_diff(petition.createdAt) }}</div>
    </div>
</div>

<div class="col-md-10" id="js-messages-wrapper">
    {% if petition.petitionMessages is not empty %}
        {% for message in petition.petitionMessages %}
            <div class="card my-3">
                <div class="card-header">
                    {% if message.owner.imageFilename %}
                        <a href="{{ uploaded_asset(message.owner.imagePath) }}" target="_blank">
                            <img class="img-fluid image-circle image-border" width="25" height="25" src="{{ uploaded_asset(message.owner.thumbImagePath) }}">
                        </a>
                    {% else %}
                        <a href="{{ asset('img/users/default.png') }}" target="_blank">
                            <img class="img-fluid image-circle image-border" width="25" height="25" src="{{ asset('img/users/default.png') }}">
                        </a>
                    {% endif %}  
                    <b class="text-purple">{{ message.owner.login }}</b>
                    <span class="float-right text-muted">{{ time_diff(message.createdAt) }}</span>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            {{ message.content }}
                        </div>
                        {% if message.readedAt and message.owner is same as(app.user) %}
                            <div class="col-12 text-right text-muted">
                                Readed {{ time_diff(message.readedAt) }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% if petition.status is not same as('Closed') %}
    <div class="col-md-10">
        <div class="card text-white bg-dark">
            <div class="card-header p-0">
                <b>Add message</b>
            </div>
            <div class="card-body p-0">
                <textarea class="bg-dark text-left text-white w-100" id="js-message-text" rows="4" style="resize: none"></textarea>
                <button class="btn btn-primary float-right" role="button" id="js-send-message">
                    <span class="fas fa-paper-plane"></span>
                    Send
                </button>
            </div>
        </div>
    </div>
{% endif %}

{{ include('js_templates/petition_messages.html.twig') }}
<script>
    let defaultUserImage = "{{ asset('img/users/default.png') }}";
    let baseAsset = "{{ uploaded_asset('') }}";
    const petitionId = "{{ petition.id }}";
</script>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.min.js"></script>
    
    <script type="module" src="{{ asset('js/helpers/_errorHelper.js') }}"></script>
    <script type="module" src="{{ asset('js/helpers/_validationHelper.js') }}"></script>
    <script type="module" src="{{ asset('js/_petitionApi.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            let $wrapper = $('#js-petition-wrapper');
            let petitionApi = new PetitionApi($wrapper, petitionId, defaultUserImage, baseAsset);
        });
    </script>

{% endblock %}